##### loading a vary large file, there are 2 options for it 
##### 1) Processing in Chunks
<!-- chunk_size = 50000
processed_chunks = []
for chunk in pd.read_csv("massive_dataset.csv", chunksize=chunk_size):
    # Perform EDA filtering, calculations, or feature engineering on this small batch
    # Example: Keep only rows where a feature meets a certain condition
    filtered_chunk = chunk[chunk["Daily_Minutes_Spent"] > 100]
    
    # Store the highly reduced chunk
    processed_chunks.append(filtered_chunk)

final_df = pd.concat(processed_chunks, ignore_index=True)
print("Final processed shape:", final_df.shape) -->

##### 2) Downcasting datatype
<!-- optimized_dtypes = {
    "User_ID": "int32",
    "App": "category",
    "Daily_Minutes_Spent": "int16",
    "Posts_Per_Day": "int8",
    "Likes_Per_Day": "int32"
}

# 2. Read the file applying those restrictions immediately upon ingestion
df = pd.read_csv("massive_dataset.csv", dtype=optimized_dtypes)

# Check your massive memory savings
df.info(memory_usage="deep") -->

In [1]:
import pandas as pd
import os

In [2]:
print(os.getcwd())

C:\Users\Pratham Langaliya

In [4]:
df = pd.read_csv(r"E:\sculptsoft\1_June\EDA\Social Media Users.csv")

In [5]:
df.head(100)

,Platform,Owner,Primary Usage,Country,Daily Time Spent (min),Verified Account,Date Joined
0,WhatsApp,Meta,Messaging,Switzerland,113.94,Yes,2019-03-03
1,WeChat,Tencent,Messaging and social media,Madagascar,49.63,Yes,2023-09-21
2,Snapchat,Snap Inc.,Multimedia messaging,Pitcairn Islands,29.01,Yes,2020-12-13
3,Instagram,Meta,Photo and video sharing,Timor-Leste,295.43,Yes,2019-04-21
4,Threads,Meta,Text-based social networking,Bermuda,71.78,No,2015-07-14
...,...,...,...,...,...,...,...
95,Instagram,Meta,Photo and video sharing,Costa Rica,298.07,No,2016-06-20
96,LinkedIn,Microsoft,Professional networking,Mongolia,22.59,No,2019-09-28
97,WeChat,Tencent,Messaging and social media,Nepal,180.19,Yes,2021-01-03
98,YouTube,Google,Video sharing,Belarus,284.31,Yes,2022-01-27
99,Facebook,Meta,Social networking,El Salvador,85.88,No,2018-08-06

In [6]:
df.describe()

       Daily Time Spent (min)
count            10000.000000
mean               152.211145
std                 85.142750
min                  5.020000
25%                 78.920000
50%                152.735000
75%                225.642500
max                300.000000

In [7]:
print(df.isnull().sum())

Platform                  0
Owner                     0
Primary Usage             0
Country                   0
Daily Time Spent (min)    0
Verified Account          0
Date Joined               0
dtype: int64

In [8]:
df["Country"].value_counts()

Country
Congo                               82
Korea                               78
Botswana                            56
Suriname                            55
Armenia                             54
                                    ..
Russian Federation                  28
Liechtenstein                       28
Montenegro                          27
Lao People's Democratic Republic    26
Saint Kitts and Nevis               26
Name: count, Length: 243, dtype: int64

In [9]:
df2 = pd.get_dummies(df, columns = ["Country"], dtype = int)
print(df2.shape)

(10000, 249)

In [10]:
df2.head(100)

,Platform,Owner,Primary Usage,Daily Time Spent (min),Verified Account,Date Joined,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,...,Country_Uruguay,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela,Country_Vietnam,Country_Wallis and Futuna,Country_Western Sahara,Country_Yemen,Country_Zambia,Country_Zimbabwe
0,WhatsApp,Meta,Messaging,113.94,Yes,2019-03-03,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,WeChat,Tencent,Messaging and social media,49.63,Yes,2023-09-21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Snapchat,Snap Inc.,Multimedia messaging,29.01,Yes,2020-12-13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Instagram,Meta,Photo and video sharing,295.43,Yes,2019-04-21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Threads,Meta,Text-based social networking,71.78,No,2015-07-14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,Instagram,Meta,Photo and video sharing,298.07,No,2016-06-20,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
96,LinkedIn,Microsoft,Professional networking,22.59,No,2019-09-28,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
97,WeChat,Tencent,Messaging and social media,180.19,Yes,2021-01-03,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
98,YouTube,Google,Video sharing,284.31,Yes,2022-01-27,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99,Facebook,Meta,Social networking,85.88,No,2018-08-06,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [11]:
print(df2["Country_Afghanistan"].sum())

44

In [12]:
print(df2["Country_American Samoa"].sum())

46

In [13]:
df2["Date Joined"] = pd.to_datetime(df2["Date Joined"])
df2["Joining_year"] = df2["Date Joined"].dt.year

In [14]:
df2.head(10)

,Platform,Owner,Primary Usage,Daily Time Spent (min),Verified Account,Date Joined,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,...,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela,Country_Vietnam,Country_Wallis and Futuna,Country_Western Sahara,Country_Yemen,Country_Zambia,Country_Zimbabwe,Joining_year
0,WhatsApp,Meta,Messaging,113.94,Yes,2019-03-03,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019
1,WeChat,Tencent,Messaging and social media,49.63,Yes,2023-09-21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2023
2,Snapchat,Snap Inc.,Multimedia messaging,29.01,Yes,2020-12-13,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020
3,Instagram,Meta,Photo and video sharing,295.43,Yes,2019-04-21,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019
4,Threads,Meta,Text-based social networking,71.78,No,2015-07-14,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
5,X (formerly Twitter),X Corp.,Microblogging,92.82,No,2021-04-12,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2021
6,Instagram,Meta,Photo and video sharing,227.85,No,2016-06-25,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2016
7,TikTok,ByteDance,Short-form videos,44.91,Yes,2023-04-26,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2023
8,Quora,Quora Inc.,Q&A knowledge sharing,140.46,Yes,2016-04-09,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2016
9,X (formerly Twitter),X Corp.,Microblogging,235.13,No,2019-05-17,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019

In [16]:
df3 = df2.drop(columns=["Date Joined"])

In [17]:
df3.head(10)

,Platform,Owner,Primary Usage,Daily Time Spent (min),Verified Account,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,Country_Andorra,...,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela,Country_Vietnam,Country_Wallis and Futuna,Country_Western Sahara,Country_Yemen,Country_Zambia,Country_Zimbabwe,Joining_year
0,WhatsApp,Meta,Messaging,113.94,Yes,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019
1,WeChat,Tencent,Messaging and social media,49.63,Yes,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2023
2,Snapchat,Snap Inc.,Multimedia messaging,29.01,Yes,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020
3,Instagram,Meta,Photo and video sharing,295.43,Yes,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019
4,Threads,Meta,Text-based social networking,71.78,No,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
5,X (formerly Twitter),X Corp.,Microblogging,92.82,No,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2021
6,Instagram,Meta,Photo and video sharing,227.85,No,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2016
7,TikTok,ByteDance,Short-form videos,44.91,Yes,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2023
8,Quora,Quora Inc.,Q&A knowledge sharing,140.46,Yes,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2016
9,X (formerly Twitter),X Corp.,Microblogging,235.13,No,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019

In [18]:
mapping_column = {'Yes' : 1, 'No' : 0}
df3["Verified Account"] = df["Verified Account"].map(mapping_column)
df3.head(10)

,Platform,Owner,Primary Usage,Daily Time Spent (min),Verified Account,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,Country_Andorra,...,Country_Uzbekistan,Country_Vanuatu,Country_Venezuela,Country_Vietnam,Country_Wallis and Futuna,Country_Western Sahara,Country_Yemen,Country_Zambia,Country_Zimbabwe,Joining_year
0,WhatsApp,Meta,Messaging,113.94,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019
1,WeChat,Tencent,Messaging and social media,49.63,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2023
2,Snapchat,Snap Inc.,Multimedia messaging,29.01,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2020
3,Instagram,Meta,Photo and video sharing,295.43,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019
4,Threads,Meta,Text-based social networking,71.78,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
5,X (formerly Twitter),X Corp.,Microblogging,92.82,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2021
6,Instagram,Meta,Photo and video sharing,227.85,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2016
7,TikTok,ByteDance,Short-form videos,44.91,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2023
8,Quora,Quora Inc.,Q&A knowledge sharing,140.46,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2016
9,X (formerly Twitter),X Corp.,Microblogging,235.13,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2019

In [19]:
df4 = pd.get_dummies(df3, columns = ["Platform"], dtype = int)

In [20]:
df4.head(10)

,Owner,Primary Usage,Daily Time Spent (min),Verified Account,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,Country_Andorra,Country_Angola,...,Platform_Quora,Platform_Reddit,Platform_Snapchat,Platform_Telegram,Platform_Threads,Platform_TikTok,Platform_WeChat,Platform_WhatsApp,Platform_X (formerly Twitter),Platform_YouTube
0,Meta,Messaging,113.94,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,Tencent,Messaging and social media,49.63,1,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
2,Snap Inc.,Multimedia messaging,29.01,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
3,Meta,Photo and video sharing,295.43,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Meta,Text-based social networking,71.78,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
5,X Corp.,Microblogging,92.82,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
6,Meta,Photo and video sharing,227.85,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7,ByteDance,Short-form videos,44.91,1,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
8,Quora Inc.,Q&A knowledge sharing,140.46,1,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
9,X Corp.,Microblogging,235.13,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [ ]:
df4.shape

(10000, 262)

In [ ]:
df5 = pd.get_dummies(df4, columns = ["Owner"], dtype = int)

In [ ]:
df5.head(10)

,Primary Usage,Daily Time Spent (min),Verified Account,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,Country_Andorra,Country_Angola,Country_Anguilla,...,Owner_Google,Owner_Meta,Owner_Microsoft,Owner_Pinterest Inc.,Owner_Quora Inc.,Owner_Reddit Inc.,Owner_Snap Inc.,Owner_Telegram FZ LLC,Owner_Tencent,Owner_X Corp.
0,Messaging,113.94,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,Messaging and social media,49.63,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,Multimedia messaging,29.01,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,Photo and video sharing,295.43,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,Text-based social networking,71.78,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,Microblogging,92.82,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,Photo and video sharing,227.85,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,Short-form videos,44.91,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,Q&A knowledge sharing,140.46,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9,Microblogging,235.13,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
df6 = df5.drop(columns=["Primary Usage"])

In [ ]:
df6.head(10)

,Daily Time Spent (min),Verified Account,Country_Afghanistan,Country_Albania,Country_Algeria,Country_American Samoa,Country_Andorra,Country_Angola,Country_Anguilla,Country_Antarctica (the territory South of 60 deg S),...,Owner_Google,Owner_Meta,Owner_Microsoft,Owner_Pinterest Inc.,Owner_Quora Inc.,Owner_Reddit Inc.,Owner_Snap Inc.,Owner_Telegram FZ LLC,Owner_Tencent,Owner_X Corp.
0,113.94,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
1,49.63,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,29.01,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,295.43,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,71.78,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
5,92.82,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
6,227.85,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
7,44.91,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8,140.46,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
9,235.13,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,1

In [ ]:
df6.shape

(10000, 271)