In [6]:
import pandas as pd
df = pd.read_csv(r"E:\sculptsoft\20 July\Churn_Modelling.csv")
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.drop(columns = ['RowNumber','CustomerId','Surname'],inplace=True)
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [8]:
df["Geography"].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [9]:
df = pd.get_dummies(df,columns=['Geography','Gender'],drop_first=True)
df.head()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,True,False

In [10]:
X = df.drop(columns=["Exited"])
y = df["Exited"]

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_trf = scaler.fit_transform(X_train)
X_test_trf = scaler.transform(X_test)

In [14]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense

In [13]:
!pip install tensorflow

Collecting tensorflow
  Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl.metadata (4.5 kB)
Collecting absl-py>=1.0.0 (from tensorflow)
  Downloading absl_py-2.5.0-py3-none-any.whl.metadata (3.3 kB)
Collecting astunparse>=1.6.0 (from tensorflow)
  Using cached astunparse-1.6.3-py2.py3-none-any.whl.metadata (4.4 kB)
Collecting flatbuffers>=25.9.23 (from tensorflow)
  Using cached flatbuffers-25.12.19-py2.py3-none-any.whl.metadata (1.0 kB)
Collecting gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 (from tensorflow)
  Downloading gast-0.7.0-py3-none-any.whl.metadata (1.5 kB)
Collecting google_pasta>=0.1.1 (from tensorflow)
  Using cached google_pasta-0.2.0-py3-none-any.whl.metadata (814 bytes)
Collecting libclang>=13.0.0 (from tensorflow)
  Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl.metadata (5.3 kB)
Collecting opt_einsum>=2.3.2 (from tensorflow)
  Using cached opt_einsum-3.4.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: packaging in c:\anaconda3\lib\site-packages (from tensorflow) (24.2)
Collecting protobuf<8.0.0,>=6.31.1 (from tensorflow)
  Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Requirement already satisfied: requests<3,>=2.21.0 in c:\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting termcolor>=1.1.0 (from tensorflow)
  Downloading termcolor-3.3.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\anaconda3\lib\site-packages (from tensorflow) (4.12.2)
Requirement already satisfied: wrapt>=1.11.0 in c:\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Collecting grpcio<2.0,>=1.24.3 (from tensorflow)
  Downloading grpcio-1.82.1-cp313-cp313-win_amd64.whl.metadata (3.8 kB)
Collecting keras>=3.12.0 (from tensorflow)
  Downloading keras-3.15.0-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: numpy>=1.26.0 in c:\anaconda3\lib\site-packages (from tensorflow) (2.5.0)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in c:\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Collecting ml_dtypes<1.0.0,>=0.5.1 (from tensorflow)
  Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl.metadata (9.2 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.5.20)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\anaconda3\lib\site-packages (from keras>=3.12.0->tensorflow) (13.9.4)
Collecting namex (from keras>=3.12.0->tensorflow)
  Using cached namex-0.1.0-py3-none-any.whl.metadata (322 bytes)
Collecting optree (from keras>=3.12.0->tensorflow)
  Downloading optree-0.19.1-cp313-cp313-win_amd64.whl.metadata (32 kB)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\anaconda3\lib\site-packages (from rich->keras>=3.12.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.0)
Downloading tensorflow-2.21.0-cp313-cp313-win_amd64.whl (351.2 MB)
   ---------------------------------------- 0.0/351.2 MB ? eta -:--:--
   ---------------------------------------- 1.6/351.2 MB 9.5 MB/s eta 0:00:37
   ---------------------------------------- 4.2/351.2 MB 11.1 MB/s eta 0:00:32
    --------------------------------------- 7.3/351.2 MB 12.4 MB/s eta 0:00:28
   - -------------------------------------- 10.7/351.2 MB 13.3 MB/s eta 0:00:26
   - -------------------------------------- 14.4/351.2 MB 14.1 MB/s eta 0:00:24
   -- ------------------------------------- 18.6/351.2 MB 15.1 MB/s eta 0:00:23
   -- ------------------------------------- 22.5/351.2 MB 15.4 MB/s eta 0:00:22
   --- ------------------------------------ 26.7/351.2 MB 16.0 MB/s eta 0:00:21
   --- ------------------------------------ 31.5/351.2 MB 16.7 MB/s eta 0:00:20
   ---- ----------------------------------- 35.9/351.2 MB 17.1 MB/s eta 0:00:19
   ---- ----------------------------------- 40.9/351.2 MB 17.6 MB/s eta 0:00:18
   ----- ---------------------------------- 45.6/351.2 MB 18.0 MB/s eta 0:00:17
   ----- ---------------------------------- 50.9/351.2 MB 18.5 MB/s eta 0:00:17
   ------ --------------------------------- 55.6/351.2 MB 18.8 MB/s eta 0:00:16
   ------ --------------------------------- 60.3/351.2 MB 19.0 MB/s eta 0:00:16
   ------- -------------------------------- 65.3/351.2 MB 19.3 MB/s eta 0:00:15
   ------- -------------------------------- 70.0/351.2 MB 19.4 MB/s eta 0:00:15
   -------- ------------------------------- 74.7/351.2 MB 19.6 MB/s eta 0:00:15
   --------- ------------------------------ 80.2/351.2 MB 20.0 MB/s eta 0:00:14
   --------- ------------------------------ 84.1/351.2 MB 19.9 MB/s eta 0:00:14
   ---------- ----------------------------- 89.4/351.2 MB 20.1 MB/s eta 0:00:14
   ---------- ----------------------------- 95.2/351.2 MB 20.4 MB/s eta 0:00:13
   ----------- --------------------------- 100.7/351.2 MB 20.6 MB/s eta 0:00:13
   ----------- --------------------------- 105.1/351.2 MB 20.6 MB/s eta 0:00:12
   ------------ -------------------------- 110.1/351.2 MB 20.7 MB/s eta 0:00:12
   ------------ -------------------------- 115.9/351.2 MB 20.9 MB/s eta 0:00:12
   ------------- ------------------------- 121.6/351.2 MB 21.1 MB/s eta 0:00:11
   -------------- ------------------------ 127.4/351.2 MB 21.4 MB/s eta 0:00:11
   -------------- ------------------------ 133.2/351.2 MB 21.6 MB/s eta 0:00:11
   --------------- ----------------------- 138.4/351.2 MB 21.6 MB/s eta 0:00:10
   ---------------- ---------------------- 144.4/351.2 MB 21.8 MB/s eta 0:00:10
   ---------------- ---------------------- 149.9/351.2 MB 22.0 MB/s eta 0:00:10
   ----------------- --------------------- 156.0/351.2 MB 22.1 MB/s eta 0:00:09
   ----------------- --------------------- 161.7/351.2 MB 22.3 MB/s eta 0:00:09
   ------------------ -------------------- 167.0/351.2 MB 22.3 MB/s eta 0:00:09
   ------------------- ------------------- 173.3/351.2 MB 22.5 MB/s eta 0:00:08
   ------------------- ------------------- 178.5/351.2 MB 22.6 MB/s eta 0:00:08
   -------------------- ------------------ 184.3/351.2 MB 22.7 MB/s eta 0:00:08
   --------------------- ----------------- 189.5/351.2 MB 22.7 MB/s eta 0:00:08
   --------------------- ----------------- 195.3/351.2 MB 22.8 MB/s eta 0:00:07
   ---------------------- ---------------- 199.0/351.2 MB 22.7 MB/s eta 0:00:07
   ---------------------- ---------------- 201.9/351.2 MB 22.4 MB/s eta 0:00:07
   ---------------------- ---------------- 205.8/351.2 MB 22.4 MB/s eta 0:00:07
   ----------------------- --------------- 211.6/351.2 MB 22.5 MB/s eta 0:00:07
   ------------------------ -------------- 217.3/351.2 MB 22.5 MB/s eta 0:00:06
   ------------------------ -------------- 223.9/351.2 MB 22.7 MB/s eta 0:00:06
   ------------------------- ------------- 229.4/351.2 MB 22.8 MB/s eta 0:00:06
   -------------------------- ------------ 235.4/351.2 MB 22.9 MB/s eta 0:00:06
   -------------------------- ------------ 240.6/351.2 MB 22.9 MB/s eta 0:00:05
   --------------------------- ----------- 246.2/351.2 MB 23.0 MB/s eta 0:00:05
   ---------------------------- ---------- 252.4/351.2 MB 23.1 MB/s eta 0:00:05
   ---------------------------- ---------- 258.2/351.2 MB 23.2 MB/s eta 0:00:05
   ----------------------------- --------- 263.7/351.2 MB 23.4 MB/s eta 0:00:04
   ----------------------------- --------- 270.0/351.2 MB 23.9 MB/s eta 0:00:04
   ------------------------------ -------- 276.0/351.2 MB 24.3 MB/s eta 0:00:04
   ------------------------------- ------- 282.1/351.2 MB 24.5 MB/s eta 0:00:03
   -------------------------------- ------ 288.6/351.2 MB 24.8 MB/s eta 0:00:03
   -------------------------------- ------ 295.2/351.2 MB 25.0 MB/s eta 0:00:03
   --------------------------------- ----- 301.2/351.2 MB 25.2 MB/s eta 0:00:02
   ---------------------------------- ---- 307.2/351.2 MB 25.3 MB/s eta 0:00:02
   ---------------------------------- ---- 313.5/351.2 MB 25.4 MB/s eta 0:00:02
   ----------------------------------- --- 319.6/351.2 MB 25.5 MB/s eta 0:00:02
   ------------------------------------ -- 325.6/351.2 MB 25.7 MB/s eta 0:00:01
   ------------------------------------ -- 332.1/351.2 MB 25.9 MB/s eta 0:00:01
   ------------------------------------- - 338.4/351.2 MB 26.0 MB/s eta 0:00:01
   --------------------------------------  344.5/351.2 MB 26.0 MB/s eta 0:00:01
   --------------------------------------  350.7/351.2 MB 26.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 26.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 26.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 26.3 MB/s eta 0:00:01
   --------------------------------------  351.0/351.2 MB 26.3 MB/s eta 0:00:01
   --------------------------------------- 351.2/351.2 MB 24.0 MB/s eta 0:00:00
Downloading grpcio-1.82.1-cp313-cp313-win_amd64.whl (5.0 MB)
   ---------------------------------------- 0.0/5.0 MB ? eta -:--:--
   ---------------------------------------  5.0/5.0 MB 28.6 MB/s eta 0:00:01
   ---------------------------------------- 5.0/5.0 MB 22.3 MB/s eta 0:00:00
Downloading ml_dtypes-0.5.4-cp313-cp313-win_amd64.whl (212 kB)
Using cached protobuf-7.35.1-cp310-abi3-win_amd64.whl (439 kB)
Downloading absl_py-2.5.0-py3-none-any.whl (137 kB)
Using cached astunparse-1.6.3-py2.py3-none-any.whl (12 kB)
Using cached flatbuffers-25.12.19-py2.py3-none-any.whl (26 kB)
Downloading gast-0.7.0-py3-none-any.whl (22 kB)
Using cached google_pasta-0.2.0-py3-none-any.whl (57 kB)
Downloading keras-3.15.0-py3-none-any.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 19.3 MB/s eta 0:00:00
Using cached libclang-18.1.1-py2.py3-none-win_amd64.whl (26.4 MB)
Using cached opt_einsum-3.4.0-py3-none-any.whl (71 kB)
Downloading termcolor-3.3.0-py3-none-any.whl (7.7 kB)
Using cached namex-0.1.0-py3-none-any.whl (5.9 kB)
Downloading optree-0.19.1-cp313-cp313-win_amd64.whl (343 kB)
Installing collected packages: namex, libclang, flatbuffers, termcolor, protobuf, optree, opt_einsum, ml_dtypes, grpcio, google_pasta, gast, astunparse, absl-py, keras, tensorflow

   -- -------------------------------------  1/15 [libclang]
   -- -------------------------------------  1/15 [libclang]
   -- -------------------------------------  1/15 [libclang]
   -- -------------------------------------  1/15 [libclang]
   -- -------------------------------------  1/15 [libclang]
   -- -------------------------------------  1/15 [libclang]
   ----- ----------------------------------  2/15 [flatbuffers]
   ----- ----------------------------------  2/15 [flatbuffers]
   -------- -------------------------------  3/15 [termcolor]
  Attempting uninstall: protobuf
   -------- -------------------------------  3/15 [termcolor]
    Found existing installation: protobuf 5.29.3
   -------- -------------------------------  3/15 [termcolor]
   ---------- -----------------------------  4/15 [protobuf]
    Uninstalling protobuf-5.29.3:
   ---------- -----------------------------  4/15 [protobuf]
      Successfully uninstalled protobuf-5.29.3
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ---------- -----------------------------  4/15 [protobuf]
   ------------- --------------------------  5/15 [optree]
   ------------- --------------------------  5/15 [optree]
   ------------- --------------------------  5/15 [optree]
   ------------- --------------------------  5/15 [optree]
   ------------- --------------------------  5/15 [optree]
   ---------------- -----------------------  6/15 [opt_einsum]
   ---------------- -----------------------  6/15 [opt_einsum]
   ---------------- -----------------------  6/15 [opt_einsum]
   ---------------- -----------------------  6/15 [opt_einsum]
   ---------------- -----------------------  6/15 [opt_einsum]
   ---------------- -----------------------  6/15 [opt_einsum]
   ---------------- -----------------------  6/15 [opt_einsum]
   ------------------ ---------------------  7/15 [ml_dtypes]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   --------------------- ------------------  8/15 [grpcio]
   ------------------------ ---------------  9/15 [google_pasta]
   ------------------------ ---------------  9/15 [google_pasta]
   ------------------------ ---------------  9/15 [google_pasta]
   ------------------------ ---------------  9/15 [google_pasta]
   ------------------------ ---------------  9/15 [google_pasta]
   ------------------------ ---------------  9/15 [google_pasta]
   -------------------------- ------------- 10/15 [gast]
   ----------------------------- ---------- 11/15 [astunparse]
   -------------------------------- ------- 12/15 [absl-py]
   -------------------------------- ------- 12/15 [absl-py]
   -------------------------------- ------- 12/15 [absl-py]
   -------------------------------- ------- 12/15 [absl-py]
   -------------------------------- ------- 12/15 [absl-py]
   -------------------------------- ------- 12/15 [absl-py]
   -------------------------------- ------- 12/15 [absl-py]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]
   ---------------------------------- ----- 13/15 [keras]

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
streamlit 1.45.1 requires pandas<3,>=1.4.0, but you have pandas 3.0.3 which is incompatible.
streamlit 1.45.1 requires protobuf<7,>=3.20, but you have protobuf 7.35.1 which is incompatible.

In [15]:
model = Sequential()

model.add(Dense(11,activation='sigmoid',input_dim=11))
model.add(Dense(11,activation='sigmoid'))
model.add(Dense(1,activation='sigmoid'))

C:\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 11)                  │             132 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              12 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 276 (1.08 KB)

 Trainable params: 276 (1.08 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
from tensorflow.keras.optimizers import SGD

model.compile(
    optimizer=SGD(learning_rate=0.01),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [19]:
history = model.fit(X_train,y_train,batch_size=50,epochs=100,verbose=1,validation_split=0.2)

Epoch 1/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7753 - loss: 0.5764 - val_accuracy: 0.7987 - val_loss: 0.5185
Epoch 2/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5177 - val_accuracy: 0.7987 - val_loss: 0.5059
Epoch 3/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5107 - val_accuracy: 0.7987 - val_loss: 0.5027
Epoch 4/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5094 - val_accuracy: 0.7987 - val_loss: 0.5018
Epoch 5/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5092 - val_accuracy: 0.7987 - val_loss: 0.5017
Epoch 6/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5091 - val_accuracy: 0.7987 - val_loss: 0.5016
Epoch 7/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5090 - val_accuracy: 0.7987 - val_loss: 0.5014
Epoch 8/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5090 - val_accuracy: 0.7987 - val_loss: 0.5014
Epoch 9/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5089 - val_accuracy: 0.7987 - val_loss: 0.5013
Epoch 10/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5088 - val_accuracy: 0.7987 - val_loss: 0.5013
Epoch 11/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5088 - val_accuracy: 0.7987 - val_loss: 0.5012
Epoch 12/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5087 - val_accuracy: 0.7987 - val_loss: 0.5011
Epoch 13/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5087 - val_accuracy: 0.7987 - val_loss: 0.5010
Epoch 14/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5086 - val_accuracy: 0.7987 - val_loss: 0.5009
Epoch 15/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5085 - val_accuracy: 0.7987 - val_loss: 0.5008
Epoch 16/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5084 - val_accuracy: 0.7987 - val_loss: 0.5008
Epoch 17/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5084 - val_accuracy: 0.7987 - val_loss: 0.5008
Epoch 18/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5083 - val_accuracy: 0.7987 - val_loss: 0.5006
Epoch 19/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5083 - val_accuracy: 0.7987 - val_loss: 0.5006
Epoch 20/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5082 - val_accuracy: 0.7987 - val_loss: 0.5005
Epoch 21/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5082 - val_accuracy: 0.7987 - val_loss: 0.5004
Epoch 22/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5081 - val_accuracy: 0.7987 - val_loss: 0.5003
Epoch 23/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5080 - val_accuracy: 0.7987 - val_loss: 0.5002
Epoch 24/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5080 - val_accuracy: 0.7987 - val_loss: 0.5001
Epoch 25/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5079 - val_accuracy: 0.7987 - val_loss: 0.5001
Epoch 26/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5078 - val_accuracy: 0.7987 - val_loss: 0.5001
Epoch 27/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5078 - val_accuracy: 0.7987 - val_loss: 0.4999
Epoch 28/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5078 - val_accuracy: 0.7987 - val_loss: 0.5001
Epoch 29/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5077 - val_accuracy: 0.7987 - val_loss: 0.5000
Epoch 30/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5077 - val_accuracy: 0.7987 - val_loss: 0.4999
Epoch 31/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5076 - val_accuracy: 0.7987 - val_loss: 0.4999
Epoch 32/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5076 - val_accuracy: 0.7987 - val_loss: 0.4998
Epoch 33/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5075 - val_accuracy: 0.7987 - val_loss: 0.4998
Epoch 34/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5075 - val_accuracy: 0.7987 - val_loss: 0.4996
Epoch 35/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5074 - val_accuracy: 0.7987 - val_loss: 0.4996
Epoch 36/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5073 - val_accuracy: 0.7987 - val_loss: 0.4995
Epoch 37/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7934 - loss: 0.5073 - val_accuracy: 0.7987 - val_loss: 0.4994
Epoch 38/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7934 - loss: 0.5072 - val_accuracy: 0.7987 - val_loss: 0.4994
Epoch 39/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5072 - val_accuracy: 0.7987 - val_loss: 0.4993
Epoch 40/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5071 - val_accuracy: 0.7987 - val_loss: 0.4993
Epoch 41/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5071 - val_accuracy: 0.7987 - val_loss: 0.4992
Epoch 42/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5070 - val_accuracy: 0.7987 - val_loss: 0.4991
Epoch 43/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5070 - val_accuracy: 0.7987 - val_loss: 0.4991
Epoch 44/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5069 - val_accuracy: 0.7987 - val_loss: 0.4990
Epoch 45/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5069 - val_accuracy: 0.7987 - val_loss: 0.4989
Epoch 46/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5068 - val_accuracy: 0.7987 - val_loss: 0.4989
Epoch 47/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5068 - val_accuracy: 0.7987 - val_loss: 0.4988
Epoch 48/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5067 - val_accuracy: 0.7987 - val_loss: 0.4988
Epoch 49/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5067 - val_accuracy: 0.7987 - val_loss: 0.4988
Epoch 50/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5067 - val_accuracy: 0.7987 - val_loss: 0.4987
Epoch 51/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5066 - val_accuracy: 0.7987 - val_loss: 0.4986
Epoch 52/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5065 - val_accuracy: 0.7987 - val_loss: 0.4985
Epoch 53/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7934 - loss: 0.5065 - val_accuracy: 0.7987 - val_loss: 0.4985
Epoch 54/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5064 - val_accuracy: 0.7987 - val_loss: 0.4984
Epoch 55/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5064 - val_accuracy: 0.7987 - val_loss: 0.4983
Epoch 56/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5063 - val_accuracy: 0.7987 - val_loss: 0.4983
Epoch 57/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5063 - val_accuracy: 0.7987 - val_loss: 0.4982
Epoch 58/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5063 - val_accuracy: 0.7987 - val_loss: 0.4982
Epoch 59/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5062 - val_accuracy: 0.7987 - val_loss: 0.4981
Epoch 60/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5062 - val_accuracy: 0.7987 - val_loss: 0.4981
Epoch 61/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5061 - val_accuracy: 0.7987 - val_loss: 0.4980
Epoch 62/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5061 - val_accuracy: 0.7987 - val_loss: 0.4979
Epoch 63/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7934 - loss: 0.5060 - val_accuracy: 0.7987 - val_loss: 0.4980
Epoch 64/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5060 - val_accuracy: 0.7987 - val_loss: 0.4979
Epoch 65/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5060 - val_accuracy: 0.7987 - val_loss: 0.4978
Epoch 66/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5059 - val_accuracy: 0.7987 - val_loss: 0.4978
Epoch 67/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5059 - val_accuracy: 0.7987 - val_loss: 0.4977
Epoch 68/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5058 - val_accuracy: 0.7987 - val_loss: 0.4976
Epoch 69/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5058 - val_accuracy: 0.7987 - val_loss: 0.4976
Epoch 70/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5058 - val_accuracy: 0.7987 - val_loss: 0.4975
Epoch 71/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5057 - val_accuracy: 0.7987 - val_loss: 0.4976
Epoch 72/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5057 - val_accuracy: 0.7987 - val_loss: 0.4974
Epoch 73/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5056 - val_accuracy: 0.7987 - val_loss: 0.4974
Epoch 74/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5056 - val_accuracy: 0.7987 - val_loss: 0.4974
Epoch 75/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5056 - val_accuracy: 0.7987 - val_loss: 0.4973
Epoch 76/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5055 - val_accuracy: 0.7987 - val_loss: 0.4972
Epoch 77/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5055 - val_accuracy: 0.7987 - val_loss: 0.4972
Epoch 78/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5054 - val_accuracy: 0.7987 - val_loss: 0.4971
Epoch 79/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5054 - val_accuracy: 0.7987 - val_loss: 0.4971
Epoch 80/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5054 - val_accuracy: 0.7987 - val_loss: 0.4971
Epoch 81/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5053 - val_accuracy: 0.7987 - val_loss: 0.4972
Epoch 82/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5054 - val_accuracy: 0.7987 - val_loss: 0.4973
Epoch 83/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5053 - val_accuracy: 0.7987 - val_loss: 0.4972
Epoch 84/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5053 - val_accuracy: 0.7987 - val_loss: 0.4971
Epoch 85/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5052 - val_accuracy: 0.7987 - val_loss: 0.4970
Epoch 86/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5052 - val_accuracy: 0.7987 - val_loss: 0.4970
Epoch 87/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5052 - val_accuracy: 0.7987 - val_loss: 0.4969
Epoch 88/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5052 - val_accuracy: 0.7987 - val_loss: 0.4969
Epoch 89/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5051 - val_accuracy: 0.7987 - val_loss: 0.4968
Epoch 90/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5051 - val_accuracy: 0.7987 - val_loss: 0.4969
Epoch 91/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5050 - val_accuracy: 0.7987 - val_loss: 0.4968
Epoch 92/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5050 - val_accuracy: 0.7987 - val_loss: 0.4967
Epoch 93/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5050 - val_accuracy: 0.7987 - val_loss: 0.4967
Epoch 94/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5049 - val_accuracy: 0.7987 - val_loss: 0.4967
Epoch 95/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5049 - val_accuracy: 0.7987 - val_loss: 0.4967
Epoch 96/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5049 - val_accuracy: 0.7987 - val_loss: 0.4966
Epoch 97/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.7934 - loss: 0.5048 - val_accuracy: 0.7987 - val_loss: 0.4965
Epoch 98/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5048 - val_accuracy: 0.7987 - val_loss: 0.4964
Epoch 99/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7934 - loss: 0.5048 - val_accuracy: 0.7987 - val_loss: 0.4965
Epoch 100/100
128/128 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7934 - loss: 0.5047 - val_accuracy: 0.7987 - val_loss: 0.4964

In [20]:
y_pred = model.predict(X_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [ ]:
y_pred = (y_pred > 0.5).astype(int)

In [25]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.8035