In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

C:\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [2]:
df = pd.read_csv(r"E:\sculptsoft\27 July\train.csv\train.csv")
df.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [3]:
df.shape

(404290, 6)

In [4]:
small_df = df.sample(100000)
small_df.head()

,id,qid1,qid2,question1,question2,is_duplicate
263712,263712,380302,380303,Would a girl lie about loving you?,"If you are dreaming about a girl, are you in l...",0
398899,398899,532142,532143,What is the best strategy to launch a niche ec...,What's it like to work at AMC Entertainment fo...,0
244306,244306,25184,118171,What is the most upvoted answer of all time on...,What is a top voted answer on Quora?,1
273072,273072,63784,125452,"What's the difference between ""for"" and ""to""?",What is the difference between to and for?,1
16983,16983,2323,1934,How can I improve my spoken English?,How can I understand english?,1

In [5]:
small_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [6]:
question_df = small_df[["question1", "question2"]]
question_df.head()

,question1,question2
263712,Would a girl lie about loving you?,"If you are dreaming about a girl, are you in l..."
398899,What is the best strategy to launch a niche ec...,What's it like to work at AMC Entertainment fo...
244306,What is the most upvoted answer of all time on...,What is a top voted answer on Quora?
273072,"What's the difference between ""for"" and ""to""?",What is the difference between to and for?
16983,How can I improve my spoken English?,How can I understand english?

In [7]:
correct_questions = (
    question_df["question1"].tolist() + question_df["question2"].tolist()
)

In [8]:
print(f"Total items in list: {len(correct_questions)}\n")
print("First 4 items (Question 1s):", correct_questions[:4])
print("Last 4 items (Question 2s):", correct_questions[4:])

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)